### ISSUE TITLE
[LATAM > US] Lead Python Developer @ Jobsity

### ISSUE THREAD

**Issue by TamaraEscobar** [pydevbr/vagas#10]
Hello, everyone! 😁

I am an IT Sourcer working for Jobsity - an american staffing company that works with lots of different clients in the US, Canada and Europe. Our specialty is to find the perfect match between our client's needs with LATAM developers. We have connected more than 400 people with international employment. 👌

### Descrição da vaga

We’re looking for a **backend engineer** who will be working closely with our Head of Engineering.

In the role, you will be responsible for **helping to design, plan, and implement** the backend services and tooling that power our SaaS platform. You will also be a **leader**, helping lead our team and especially our BE architecture and engineers. 😎

### Local

Fully Remote.

### Requisitos

- Strong and deep experience writing scalable Django backends, working with relational databases (Postgres).
- Engineering GraphQL APIs
- Experience with end-to-end ownership of built systems.

- Experience in DevOps/SRE practices such as:
Deployments
Managing incident response
Log and monitoring
Debugging in production.

- Expertise in architectural design patterns.
- Previous experience managing teams and communicating with stakeholders.
- +C1 Advanced English level 🗣

**Bonus skills:**
- Experience with React + Typescript
- Experience with Hasura
- Experience with Vercel
- Experience with Fly.io 

### Benefícios

🔹15 business days of paid vacation yearly.
🔹3 extra off days per year.
🔹Paid local holidays.
🔹Unlimited PTOs.
🔹Learning budget.
🔹Financing program for equipment and home office supplies.
🔹Betterfly app (wellness).
🔹Bonuses for referrals and more!

### Contratação

We offer full-time, long-term, 100% remote, and contractor (American contract) positions with USD payments + benefits within an international team and working on international client projects! 🌎

### Como se candidatar

If you're interested, please reach out to me on [Linkedin](https://www.linkedin.com/in/tamaraescobar-/)  or send me an email with your LinkedIn profile & updated Resume **IN ENGLISH** at tamara.escobar@jobsity.com with "Lead Python" as the subject.

### Alocação

- [ ] Alocado
- [X] Remoto
- [ ] Presencial
- [ ] Híbrido

### Regime

- [ ] CLT
- [ ] Estágio
- [ ] Freela
- [ ] PJ
- [ ] Cooperado

### Nível

- [ ] Júnior
- [ ] Pleno
- [X] Sênior
- [ ] Especialista

### Período

- [X] Full time
- [ ] Part Time
- [ ] Projeto

### Remuneração

R$ 15k - R$ 20k

**Comment by AngelaBarboza** [comment]
Hello!✨
This week we're still looking for a Lead Python Developer to join our team! 🚀

We also have a referrals program at Jobsity (https://careers.jobsity.com/referral-program).
So if your friend gets hired YOU get a bonus 😉🤩
