### ISSUE TITLE
[100% Home Office] Python Developer @Geobyte

### ISSUE THREAD

**Issue by Tayrangel** [pydevbr/vagas#4]
### Nossa empresa

Geobyte Consultoria e Tecnologia

### Descrição da vaga

O líder técnico deve trabalhar em conjunto com a equipe de desenvolvimento e com a equipe de negócios para aplicar soluções técnicas escaláveis, confiáveis e adequadas aos produtos. Para isso é necessário que o profissional tenha o conhecimento técnico, capacidade de decisão, seja responsável, criativo e tenha visão estratégica.

### Local

100% Home Office

#### Obrigatórios:
Python; (Mínimo 3 anos de experiência recente)
Django; (Mínimo 2 anos de experiência recente)
Django Rest Framework;
PostgreSQL (postgis);
Docker;
Linux;

### Desejáveis:
Conhecer geoprocessamento com django (GeoDjango);
Conhecer Geoserver.

### Benefícios

Home office

### Contratação

PJ

### Como se candidatar

https://www.linkedin.com/jobs/view/3425793879

### Alocação

- [ ] Alocado
- [X] Remoto
- [ ] Presencial
- [ ] Híbrido

### Regime

- [ ] CLT
- [ ] Estágio
- [ ] Freela
- [X] PJ
- [ ] Cooperado

### Nível

- [ ] Júnior
- [X] Pleno
- [X] Sênior
- [X] Especialista

### Período

- [X] Full time
- [ ] Part Time
- [ ] Projeto

### Remuneração

None

**Comment by GabrielYudenich** [comment]
A vaga já está fechada. Tentei me candidatar mas não aceitam mais candidaturas.

**Comment by Tayrangel** [comment]
> A vaga já está fechada. Tentei me candidatar mas não aceitam mais candidaturas.

@GabrielYudenich foi contratado uma pessoa essa semana. Mas se ainda tiver interesse, entre em contato com a empresa pelo LinkedIn, pois existe um banco de talentos.

**Comment by GabrielYudenich** [comment]
Ah perfeito!
Vou entrar em contato sim, estou desesperado por emprego

Em qua., 1 de mar. de 2023 10:09, Tayhana Marçal Rangel da Fonseca <
***@***.***> escreveu:
