### ISSUE TITLE
[Remoto] Desenvolvedor Python/Flask @ Yungas

### ISSUE THREAD

**Issue by ghedin** [pydevbr/vagas#7]
### Nossa empresa

Yungas

### Descrição da vaga

A Yungas é uma empresa de tecnologia líder em transformação digital no mercado de franquias brasileiro. Estamos em busca de pessoas com vontade de crescer e de fazer parte desse time referência!

Estamos em busca de novos engenheiros de software (+6 anos de experiência) para sustentar produtos em crescimento acelerado, concebendo melhorias e novas funcionalidades além de contribuir com a evolução da arquitetura e qualidade do código.

Você irá trabalhar no dia-a-dia principalmente com com Python/Flask no back-end, Docker, banco de dados PostgreSQL e alguns serviços da AWS.

### Local

Remoto ou no SC401 Square Corporate em Florianópolis-SC.

#### Obrigatórios:
- 3 anos de experiência com Flask
- 3 anos de experiência com PostgreSQL

### Desejáveis:
- conhecimentos em Docker
- conhecimentos em AWS

### Diferenciais:
- projetos open source

### Benefícios

- Plano de saúde
- Seguro de vida
- Caju

#### Diferenciais
- horário flexível
- oportunidade de crescimento 

### Contratação

PJ a combinar

### Como se candidatar

Enviar CV através [deste formulário](https://jobs.quickin.io/yungas/jobs/6381035df59cf50014624244?src=Github).

### Tempo médio de feedbacks

Em até 2 semanas.

### Keywords

flask python postgresql docker

### Alocação

- [ ] Alocado
- [X] Remoto
- [ ] Presencial
- [ ] Híbrido

### Regime

- [x] CLT
- [ ] Estágio
- [ ] Freela
- [X] PJ
- [ ] Cooperado

### Nível

- [ ] Júnior
- [X] Pleno
- [X] Sênior
- [ ] Especialista

### Período

- [X] Full time
- [ ] Part Time
- [ ] Projeto

### Remuneração

R$ 5k - R$ 10k

**Comment by eddyyxxyy** [comment]
Há vagas para Junior?

**Comment by augustoarraes** [comment]
O email está voltando. O Email está correto?

**Comment by ghedin** [comment]
Alterado :-)
